Exception in thread "main" java.lang.IndexOutOfBoundsException: 141
	at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:140)
	at scala.collection.immutable.Vector.apply(Vector.scala:130)
	at com.linkedin.domination.storm.Storm$$anonfun$updateCurrentPopulations$2.apply(Storm.scala:111)
	at com.linkedin.domination.storm.Storm$$anonfun$updateCurrentPopulations$2.apply(Storm.scala:110)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:95)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:95)
	at scala.collection.Iterator$class.foreach(Iterator.scala:772)
	at scala.collection.mutable.HashTable$$anon$1.foreach(HashTable.scala:157)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:190)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:45)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:95)
	at com.linkedin.domination.storm.Storm.updateCurrentPopulations(Storm.scala:110)
	at com.linkedin.domination.storm.Storm.makeMove(Storm.scala:94)
	at com.linkedin.domination.server.Game.start(Game.java:61)
	at com.linkedin.domination.server.Server.main(Server.java:226)
